services:
  - type: worker
    name: iare-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main_render.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: DEVELOPER_CHAT_ID
        sync: false
      - key: MAINTAINER_CHAT_ID
        sync: false
